### ISSUE TITLE
请教一些疑惑

### ISSUE THREAD

**Issue by leileilin** [YuweiYin/GTrans#1]
你好，我想咨询一下baseline的模型的实验结果都是你复现的吗？我看和原论文不一致。
谢谢！！！

**Comment by YuweiYin** [comment]
Thanks for reading our work! Yes, we re-implemented all baselines for a fair comparison, i.e., rule out the influence of hyper-parameter choice on model performance.

**Comment by leileilin** [comment]
> Thanks for reading our work! Yes, we re-implemented all baselines for a fair comparison, i.e., rule out the influence of hyper-parameter choice on model performance.

Thanks for your reply. I wonder if there is any plan to release the code of the related reproduced method? Because this is my first contact with the field of encoderlayerfusion, I found that the codes of many previous methods are not open source.

**Comment by YuweiYin** [comment]
We will consider releasing the core code of the reproduced baseline. The implementations of these methods are not very hard. We suggest you modify the Transformer model following the ideas of their papers. Alternatively, you can contact the authors of the baselines and request them to release their source code.

**Comment by leileilin** [comment]
> We will consider releasing the core code of the reproduced baseline. The implementations of these methods are not very hard. We suggest you modify the Transformer model following the ideas of their papers. Alternatively, you can contact the authors of the baselines and request them to release their source code.

Thanks for your reply. I'll try to reproduce the code by myself.
