### ISSUE TITLE
Where is the WMT-2014 data？

### ISSUE THREAD

**Issue by achaosss** [YuweiYin/GTrans#3]
I am a beginner, and I would like to ask where I can download the full dataset of WMT-2014. I didn't find all the data at https://www.statmt.org/wmt14/translation-task.html.

**Comment by YuweiYin** [comment]
Hi, you are on the right webpage:
https://www.statmt.org/wmt14/translation-task.html#download

DOWNLOAD -> Parallel data -> DE-EN ([Europarl v7](https://www.statmt.org/wmt13/training-parallel-europarl-v7.tgz), [Common Crawl corpus](https://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz), and [News Commentary](https://www.statmt.org/wmt14/training-parallel-nc-v9.tgz))

**Comment by achaosss** [comment]
> Hi, you are on the right webpage: https://www.statmt.org/wmt14/translation-task.html#download
> 
> DOWNLOAD -> Parallel data -> DE-EN ([Europarl v7](https://www.statmt.org/wmt13/training-parallel-europarl-v7.tgz), [Common Crawl corpus](https://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz), and [News Commentary](https://www.statmt.org/wmt14/training-parallel-nc-v9.tgz))

Thanks

**Comment by achaosss** [comment]
> Hi, you are on the right webpage: https://www.statmt.org/wmt14/translation-task.html#download
> 
> DOWNLOAD -> Parallel data -> DE-EN ([Europarl v7](https://www.statmt.org/wmt13/training-parallel-europarl-v7.tgz), [Common Crawl corpus](https://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz), and [News Commentary](https://www.statmt.org/wmt14/training-parallel-nc-v9.tgz))

I'm sorry, but I encountered another problem. 

  File "/content/GTrans/GTrans/fairseq/tasks/translation.py", line 267, in setup_task
    os.path.join(paths[0], "dict.{}.txt".format(args.source_lang))
  File "/content/GTrans/GTrans/fairseq/tasks/fairseq_task.py", line 57, in load_dictionary
    return Dictionary.load(filename)
  File "/content/GTrans/GTrans/fairseq/data/dictionary.py", line 215, in load
    d.add_from_file(f)
  File "/content/GTrans/GTrans/fairseq/data/dictionary.py", line 228, in add_from_file
    raise fnfe
  File "/content/GTrans/GTrans/fairseq/data/dictionary.py", line 225, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/content/training/dict.en.txt'. 


The downloaded dataset needs additional conversion to obtain dict.__.txt
